//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blogs
    {
        public int ID { get; set; }
        public string Header { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual AuthorNews AuthorNews { get; set; }
        public virtual BlogCategory BlogCategory { get; set; }
    }
}
