//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortfolioDB : DbContext
    {
        public PortfolioDB()
            : base("name=PortfolioDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutDiv> AboutDivs { get; set; }
        public virtual DbSet<AboutItem> AboutItems { get; set; }
        public virtual DbSet<AuthorNew> AuthorNews { get; set; }
        public virtual DbSet<BlogCategory> BlogCategories { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<CategoryWork> CategoryWorks { get; set; }
        public virtual DbSet<MyWorksDiv> MyWorksDivs { get; set; }
        public virtual DbSet<Section1Div> Section1Div { get; set; }
        public virtual DbSet<ServicesDiv> ServicesDivs { get; set; }
        public virtual DbSet<Testimony> Testimonies { get; set; }
    }
}
