//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyPortfolioDB : DbContext
    {
        public MyPortfolioDB()
            : base("name=MyPortfolioDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutDiv> AboutDiv { get; set; }
        public virtual DbSet<AboutItems> AboutItems { get; set; }
        public virtual DbSet<AuthorNews> AuthorNews { get; set; }
        public virtual DbSet<BlogCategory> BlogCategory { get; set; }
        public virtual DbSet<Blogs> Blogs { get; set; }
        public virtual DbSet<CategoryWork> CategoryWork { get; set; }
        public virtual DbSet<MyWorksDiv> MyWorksDiv { get; set; }
        public virtual DbSet<Section1Div> Section1Div { get; set; }
        public virtual DbSet<ServicesDiv> ServicesDiv { get; set; }
        public virtual DbSet<Testimony> Testimony { get; set; }
    }
}
