//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Settings
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Email yazilmayib!")]
        [EmailAddress]
        public string Email { get; set; }
        [MinLength(5)]
        [MaxLength(50)]
        [Required]
        public string Password { get; set; }
    }
}
